name: Chat App API Deployment

on:
    push:
        branches: [production]
    pull_request:
        branches: [production]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy using ssh
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  port: 22
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      cd /var/www/nodejs/chat-app-api
                      git checkout main
                      git pull
                      yarn migrate:prod
                      yarn seed:prod
                      yarn install
                      yarn build
                      pm2 restart chat-app-api
